version: '3'

services:
  db:
    container_name: db_archetype
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_archetype:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_archetype
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: "json-file"
      options:
        max-size: 500m

volumes:
  db_archetype: