version: '3'

services:
  db:
    container_name: db_archetype
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_archetype:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_archetype
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: "json-file"
      options:
        max-size: 500m

  localstack:
    container_name: insurance-account-re-batch-localstack
    image: localstack/localstack:2.3.2
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs, s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_archetype: